### PR TITLE
Fix 1898 sequence alteration

### LINKED ISSUE #1898: error when adding sequence alteration
```
2018-06-15 16:48:22,207 [Actor Thread 3] ERROR apollo.AnnotationEditorController  - CAUGHT ERROR through websocket call: java.lang.reflect.InvocationTargetException
2018-06-15 16:48:22,207 [Actor Thread 3] ERROR apollo.AnnotationEditorController  - THROWING PARENT ERROR instead through reflection: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
2018-06-15 16:48:22,208 [Actor Thread 3] ERROR apollo.AnnotationEditorController  - exception org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
2018-06-15 16:48:22,208 [Actor Thread 3] ERROR apollo.AnnotationEditorController  - exception message Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
2018-06-15 16:48:22,208 [Actor Thread 3] ERROR apollo.AnnotationEditorController  - username nathandunn@lbl.gov
2018-06-15 16:48:22,208 [Actor Thread 3] ERROR apollo.AnnotationEditorController  - error destination message: /topic/AnnotationNotification/user/myemail@abc.com
```

### PR DESCRIPTION
**Pull request by nathandunn**
fixed #1898 

Still getting:

```
Error 2018-06-15 11:38:38,795 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - CAUGHT ERROR through websocket call: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'Feature{id=67, symbol='null', description='null', name='214c25d3-ee2f-4072-b186-3c3927c0ea11', uniqueName='214c25d3-ee2f-4072-b186-3c3927c0ea11', sequenceLength=null, status=null, dateCreated=Fri Jun 15 11:38:38 PDT 2018, lastUpdated=Fri Jun 15 11:38:38 PDT 2018}' with class 'org.bbop.apollo.Insertion' to class 'org.bbop.apollo.SequenceAlterationArtifact'
| Error 2018-06-15 11:38:38,795 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - exception org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'Feature{id=67, symbol='null', description='null', name='214c25d3-ee2f-4072-b186-3c3927c0ea11', uniqueName='214c25d3-ee2f-4072-b186-3c3927c0ea11', sequenceLength=null, status=null, dateCreated=Fri Jun 15 11:38:38 PDT 2018, lastUpdated=Fri Jun 15 11:38:38 PDT 2018}' with class 'org.bbop.apollo.Insertion' to class 'org.bbop.apollo.SequenceAlterationArtifact'
| Error 2018-06-15 11:38:38,795 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - exception message Cannot cast object 'Feature{id=67, symbol='null', description='null', name='214c25d3-ee2f-4072-b186-3c3927c0ea11', uniqueName='214c25d3-ee2f-4072-b186-3c3927c0ea11', sequenceLength=null, status=null, dateCreated=Fri Jun 15 11:38:38 PDT 2018, lastUpdated=Fri Jun 15 11:38:38 PDT 2018}' with class 'org.bbop.apollo.Insertion' to class 'org.bbop.apollo.SequenceAlterationArtifact'
| Error 2018-06-15 11:38:38,796 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - username ndunn@me.com
| Error 2018-06-15 11:38:38,796 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - error destination message: /topic/AnnotationNotification/user/ndunn@me.com
```

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  I opened this, but feel free to close and fix it some other way.  I think it will require your expertise on this as the sequence alteration code appears to be overloaded with the variant annotation code.

File: grails-app/services/org/bbop/apollo/RequestHandlingService.groovy [hunk 1]
```diff
@@ -1270,8 +1270,12 @@ class RequestHandlingService {
 
         for (int i = 0; i < features.length(); ++i) {
             JSONObject jsonFeature = features.getJSONObject(i);
-            int fmin = jsonFeature.get(FeatureStringEnum.LOCATION.value).fmin
-            int fmax = jsonFeature.get(FeatureStringEnum.LOCATION.value).fmax
+            Integer fmin = jsonFeature.get(FeatureStringEnum.LOCATION.value)?.fmin
+            Integer fmax = jsonFeature.get(FeatureStringEnum.LOCATION.value)?.fmax
+            if(!fmax){
+                fmax = fmin
```
Comment (deepakunni3) [inline grails-app/services/org/bbop/apollo/RequestHandlingService.groovy]: This is an incorrect assumption.

`fmax = fmin` is valid only for insertion.
For deletion and substitution, `fmax = fmin + 1`

Shouldn't it be the responsibility of the client to provide proper `fmin` and `fmax`?
Inferring the `fmax` can only lead to problems. Instead, we should throw an AnnotationException when the incoming JSON doesn't have either the `fmin` or the `fmax`.

**Comment by deepakunni3** [comment]
The latest commit to `SequenceTrack.js` in this PR takes care of the error you were seeing.

It was because the client was sending an incorrect type in its JSON, `insertion` instead of `insertion_artifact`.
